# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo01.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 787)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#MainWindow{border-image: url(:/newfilepath/Icon/timg (3).jpg);}")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_ResNet = QtWidgets.QWidget()
        self.page_ResNet.setStyleSheet("")
        self.page_ResNet.setObjectName("page_ResNet")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_ResNet)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.page_ResNet)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(36)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 85, 0);\n"
"background:transparent;")
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.tabWidget = QtWidgets.QTabWidget(self.page_ResNet)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("#tab{border-image: url(:/newfilepath/Icon/timg (3).jpg);}")
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{background-color: rgba(206, 206, 206, 0.4);}")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(50, -1, 50, -1)
        self.gridLayout.setHorizontalSpacing(100)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.spinBox_exercise = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_exercise.setFont(font)
        self.spinBox_exercise.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_exercise.setWrapping(True)
        self.spinBox_exercise.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_exercise.setMaximum(1000)
        self.spinBox_exercise.setObjectName("spinBox_exercise")
        self.horizontalLayout_2.addWidget(self.spinBox_exercise)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.comboBox_floor = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.comboBox_floor.setFont(font)
        self.comboBox_floor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_floor.setAutoFillBackground(True)
        self.comboBox_floor.setStyleSheet("")
        self.comboBox_floor.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_floor.setObjectName("comboBox_floor")
        self.comboBox_floor.addItem("")
        self.comboBox_floor.addItem("")
        self.comboBox_floor.addItem("")
        self.comboBox_floor.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_floor)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.spinBox_numbers = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_numbers.setFont(font)
        self.spinBox_numbers.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_numbers.setWrapping(True)
        self.spinBox_numbers.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_numbers.setMaximum(1000)
        self.spinBox_numbers.setProperty("value", 1000)
        self.spinBox_numbers.setObjectName("spinBox_numbers")
        self.horizontalLayout_11.addWidget(self.spinBox_numbers)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.spinBox_epoch = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_epoch.setFont(font)
        self.spinBox_epoch.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_epoch.setWrapping(True)
        self.spinBox_epoch.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_epoch.setMaximum(1000)
        self.spinBox_epoch.setProperty("value", 200)
        self.spinBox_epoch.setObjectName("spinBox_epoch")
        self.horizontalLayout_7.addWidget(self.spinBox_epoch)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.spinBox_batch = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_batch.setFont(font)
        self.spinBox_batch.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_batch.setWrapping(True)
        self.spinBox_batch.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_batch.setMaximum(999)
        self.spinBox_batch.setSingleStep(1)
        self.spinBox_batch.setProperty("value", 16)
        self.spinBox_batch.setObjectName("spinBox_batch")
        self.horizontalLayout_9.addWidget(self.spinBox_batch)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.doubleSpinBox_LR = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.doubleSpinBox_LR.setFont(font)
        self.doubleSpinBox_LR.setAutoFillBackground(True)
        self.doubleSpinBox_LR.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.doubleSpinBox_LR.setWrapping(True)
        self.doubleSpinBox_LR.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_LR.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_LR.setDecimals(5)
        self.doubleSpinBox_LR.setMaximum(1.0)
        self.doubleSpinBox_LR.setSingleStep(1e-06)
        self.doubleSpinBox_LR.setProperty("value", 0.0001)
        self.doubleSpinBox_LR.setObjectName("doubleSpinBox_LR")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_LR)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.pushButton_ResNet_load = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_ResNet_load.setFont(font)
        self.pushButton_ResNet_load.setObjectName("pushButton_ResNet_load")
        self.horizontalLayout_8.addWidget(self.pushButton_ResNet_load)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("background: transparent;")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:none;\n"
"background-color: rgba(211, 211, 211, 0.4);\n"
"")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 894, 600))
        self.scrollAreaWidgetContents_4.setMinimumSize(QtCore.QSize(0, 600))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_16.addWidget(self.scrollArea_4)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(500, -1, 10, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ResNet = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.checkBox_ResNet.setFont(font)
        self.checkBox_ResNet.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ResNet.setAutoFillBackground(False)
        self.checkBox_ResNet.setStyleSheet("background-color: rgba(206, 206, 206, 0.4);")
        self.checkBox_ResNet.setChecked(True)
        self.checkBox_ResNet.setTristate(False)
        self.checkBox_ResNet.setObjectName("checkBox_ResNet")
        self.horizontalLayout_3.addWidget(self.checkBox_ResNet)
        self.pushButton_ResNet_train = QtWidgets.QPushButton(self.tab)
        self.pushButton_ResNet_train.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_ResNet_train.setFont(font)
        self.pushButton_ResNet_train.setObjectName("pushButton_ResNet_train")
        self.horizontalLayout_3.addWidget(self.pushButton_ResNet_train)
        self.pushButton_ResNet_cancel = QtWidgets.QPushButton(self.tab)
        self.pushButton_ResNet_cancel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_ResNet_cancel.setFont(font)
        self.pushButton_ResNet_cancel.setObjectName("pushButton_ResNet_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_ResNet_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 6)
        self.verticalLayout_3.setStretch(2, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/battery.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("#tab_2{border-image: url(:/newfilepath/Icon/timg (3).jpg);}")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_13.setSpacing(15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.lineEdit_predict_imgpath = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_predict_imgpath.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_predict_imgpath.setFont(font)
        self.lineEdit_predict_imgpath.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.lineEdit_predict_imgpath.setText("")
        self.lineEdit_predict_imgpath.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_predict_imgpath.setClearButtonEnabled(True)
        self.lineEdit_predict_imgpath.setObjectName("lineEdit_predict_imgpath")
        self.horizontalLayout_13.addWidget(self.lineEdit_predict_imgpath)
        self.pushButton_ResNet_predict_imgpath = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_ResNet_predict_imgpath.setFont(font)
        self.pushButton_ResNet_predict_imgpath.setObjectName("pushButton_ResNet_predict_imgpath")
        self.horizontalLayout_13.addWidget(self.pushButton_ResNet_predict_imgpath)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_25.setSpacing(15)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.lineEdit_predict_netpath = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_predict_netpath.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_predict_netpath.setFont(font)
        self.lineEdit_predict_netpath.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.lineEdit_predict_netpath.setText("")
        self.lineEdit_predict_netpath.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_predict_netpath.setClearButtonEnabled(True)
        self.lineEdit_predict_netpath.setObjectName("lineEdit_predict_netpath")
        self.horizontalLayout_25.addWidget(self.lineEdit_predict_netpath)
        self.pushButton_ResNet_predict_netpath = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_ResNet_predict_netpath.setFont(font)
        self.pushButton_ResNet_predict_netpath.setObjectName("pushButton_ResNet_predict_netpath")
        self.horizontalLayout_25.addWidget(self.pushButton_ResNet_predict_netpath)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background:transparent;")
        self.scrollArea.setInputMethodHints(QtCore.Qt.ImhNone)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 894, 900))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 900))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 871, 421))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 871, 391))
        self.textBrowser.setStyleSheet("border:none;\n"
"background-color: rgba(0, 255, 0, 0.05);")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 450, 871, 421))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 30, 871, 391))
        self.textBrowser_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 255, 0, 0.05);")
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(600, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_14.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_2, icon, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(170, 190, 611, 221))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(48)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background:transparent;\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/网络.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page_ResNet)
        self.page_UNet = QtWidgets.QWidget()
        self.page_UNet.setObjectName("page_UNet")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_UNet)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.page_UNet)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(36)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255, 85, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.page_UNet)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setAutoFillBackground(True)
        self.tabWidget_4.setStyleSheet("background;transparent;")
        self.tabWidget_4.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_4.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_4.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget_4.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_4.setDocumentMode(False)
        self.tabWidget_4.setTabsClosable(True)
        self.tabWidget_4.setMovable(True)
        self.tabWidget_4.setTabBarAutoHide(True)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_14)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_14)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("QGroupBox{background-color: rgba(206, 206, 206, 0.5);}")
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setContentsMargins(50, -1, 50, -1)
        self.gridLayout_3.setHorizontalSpacing(100)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_27.addWidget(self.label_26)
        self.spinBox_exercise_3 = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.spinBox_exercise_3.setFont(font)
        self.spinBox_exercise_3.setWrapping(True)
        self.spinBox_exercise_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_exercise_3.setMaximum(1000)
        self.spinBox_exercise_3.setObjectName("spinBox_exercise_3")
        self.horizontalLayout_27.addWidget(self.spinBox_exercise_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)
        self.comboBox_floor_3 = QtWidgets.QComboBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.comboBox_floor_3.setFont(font)
        self.comboBox_floor_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_floor_3.setAutoFillBackground(True)
        self.comboBox_floor_3.setStyleSheet("")
        self.comboBox_floor_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_floor_3.setObjectName("comboBox_floor_3")
        self.comboBox_floor_3.addItem("")
        self.comboBox_floor_3.addItem("")
        self.comboBox_floor_3.addItem("")
        self.comboBox_floor_3.addItem("")
        self.horizontalLayout_28.addWidget(self.comboBox_floor_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 0, 1, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_29.addWidget(self.label_28)
        self.spinBox_numbers_3 = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.spinBox_numbers_3.setFont(font)
        self.spinBox_numbers_3.setStyleSheet("")
        self.spinBox_numbers_3.setWrapping(True)
        self.spinBox_numbers_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_numbers_3.setMaximum(1000)
        self.spinBox_numbers_3.setProperty("value", 1000)
        self.spinBox_numbers_3.setObjectName("spinBox_numbers_3")
        self.horizontalLayout_29.addWidget(self.spinBox_numbers_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 0, 2, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_30.addWidget(self.label_29)
        self.spinBox_epoch_3 = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.spinBox_epoch_3.setFont(font)
        self.spinBox_epoch_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.spinBox_epoch_3.setWrapping(True)
        self.spinBox_epoch_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_epoch_3.setMaximum(1000)
        self.spinBox_epoch_3.setProperty("value", 200)
        self.spinBox_epoch_3.setObjectName("spinBox_epoch_3")
        self.horizontalLayout_30.addWidget(self.spinBox_epoch_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_30, 1, 0, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_31.addWidget(self.label_30)
        self.spinBox_batch_3 = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.spinBox_batch_3.setFont(font)
        self.spinBox_batch_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.spinBox_batch_3.setWrapping(True)
        self.spinBox_batch_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_batch_3.setMaximum(999)
        self.spinBox_batch_3.setSingleStep(1)
        self.spinBox_batch_3.setProperty("value", 64)
        self.spinBox_batch_3.setObjectName("spinBox_batch_3")
        self.horizontalLayout_31.addWidget(self.spinBox_batch_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_31, 1, 1, 1, 1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        self.label_31.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_32.addWidget(self.label_31)
        self.doubleSpinBox_LR_3 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.doubleSpinBox_LR_3.setFont(font)
        self.doubleSpinBox_LR_3.setAutoFillBackground(True)
        self.doubleSpinBox_LR_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.doubleSpinBox_LR_3.setWrapping(True)
        self.doubleSpinBox_LR_3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_LR_3.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_LR_3.setDecimals(5)
        self.doubleSpinBox_LR_3.setMaximum(1.0)
        self.doubleSpinBox_LR_3.setSingleStep(1e-06)
        self.doubleSpinBox_LR_3.setProperty("value", 0.0001)
        self.doubleSpinBox_LR_3.setObjectName("doubleSpinBox_LR_3")
        self.horizontalLayout_32.addWidget(self.doubleSpinBox_LR_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_32, 1, 2, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setSpacing(15)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_32 = QtWidgets.QLabel(self.groupBox_7)
        self.label_32.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_33.addWidget(self.label_32)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_33.addWidget(self.lineEdit_4)
        self.pushButton_ResNet_load_3 = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_ResNet_load_3.setFont(font)
        self.pushButton_ResNet_load_3.setObjectName("pushButton_ResNet_load_3")
        self.horizontalLayout_33.addWidget(self.pushButton_ResNet_load_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_33, 2, 0, 1, 3)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_14)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.tabWidget_6.setFont(font)
        self.tabWidget_6.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_15)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("border:none;\n"
"background-color: rgba(211, 211, 211, 0.1);\n"
"")
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_14.addWidget(self.textEdit_3)
        self.tabWidget_6.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.verticalLayout_keshihua_3 = QtWidgets.QVBoxLayout(self.tab_16)
        self.verticalLayout_keshihua_3.setObjectName("verticalLayout_keshihua_3")
        self.label_pic_3 = QtWidgets.QLabel(self.tab_16)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_pic_3.setFont(font)
        self.label_pic_3.setAutoFillBackground(True)
        self.label_pic_3.setText("")
        self.label_pic_3.setTextFormat(QtCore.Qt.RichText)
        self.label_pic_3.setScaledContents(True)
        self.label_pic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_3.setOpenExternalLinks(True)
        self.label_pic_3.setObjectName("label_pic_3")
        self.verticalLayout_keshihua_3.addWidget(self.label_pic_3)
        self.tabWidget_6.addTab(self.tab_16, "")
        self.verticalLayout_13.addWidget(self.tabWidget_6)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(500, -1, 10, -1)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.checkBox_ResNet_3 = QtWidgets.QCheckBox(self.tab_14)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.checkBox_ResNet_3.setFont(font)
        self.checkBox_ResNet_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ResNet_3.setAutoFillBackground(False)
        self.checkBox_ResNet_3.setChecked(True)
        self.checkBox_ResNet_3.setTristate(False)
        self.checkBox_ResNet_3.setObjectName("checkBox_ResNet_3")
        self.horizontalLayout_34.addWidget(self.checkBox_ResNet_3)
        self.pushButton_ResNet_train_3 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_ResNet_train_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_ResNet_train_3.setFont(font)
        self.pushButton_ResNet_train_3.setObjectName("pushButton_ResNet_train_3")
        self.horizontalLayout_34.addWidget(self.pushButton_ResNet_train_3)
        self.pushButton_ResNet_cancel_3 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_ResNet_cancel_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_ResNet_cancel_3.setFont(font)
        self.pushButton_ResNet_cancel_3.setObjectName("pushButton_ResNet_cancel_3")
        self.horizontalLayout_34.addWidget(self.pushButton_ResNet_cancel_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_34)
        self.verticalLayout_13.setStretch(0, 3)
        self.verticalLayout_13.setStretch(1, 6)
        self.verticalLayout_13.setStretch(2, 1)
        self.tabWidget_4.addTab(self.tab_14, icon1, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_17)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_35.setSpacing(15)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_33 = QtWidgets.QLabel(self.tab_17)
        self.label_33.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_35.addWidget(self.label_33)
        self.lineEdit_predict_imgpath_3 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_predict_imgpath_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_predict_imgpath_3.setFont(font)
        self.lineEdit_predict_imgpath_3.setText("")
        self.lineEdit_predict_imgpath_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_predict_imgpath_3.setObjectName("lineEdit_predict_imgpath_3")
        self.horizontalLayout_35.addWidget(self.lineEdit_predict_imgpath_3)
        self.pushButton_ResNet_predict_imgpath_3 = QtWidgets.QPushButton(self.tab_17)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_ResNet_predict_imgpath_3.setFont(font)
        self.pushButton_ResNet_predict_imgpath_3.setObjectName("pushButton_ResNet_predict_imgpath_3")
        self.horizontalLayout_35.addWidget(self.pushButton_ResNet_predict_imgpath_3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_36.setSpacing(15)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_34 = QtWidgets.QLabel(self.tab_17)
        self.label_34.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_36.addWidget(self.label_34)
        self.lineEdit_predict_netpath_3 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_predict_netpath_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_predict_netpath_3.setFont(font)
        self.lineEdit_predict_netpath_3.setText("")
        self.lineEdit_predict_netpath_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_predict_netpath_3.setObjectName("lineEdit_predict_netpath_3")
        self.horizontalLayout_36.addWidget(self.lineEdit_predict_netpath_3)
        self.pushButton_ResNet_predict_netpath_3 = QtWidgets.QPushButton(self.tab_17)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_ResNet_predict_netpath_3.setFont(font)
        self.pushButton_ResNet_predict_netpath_3.setObjectName("pushButton_ResNet_predict_netpath_3")
        self.horizontalLayout_36.addWidget(self.pushButton_ResNet_predict_netpath_3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_36)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_17)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.scrollArea_3.setFont(font)
        self.scrollArea_3.setMouseTracking(False)
        self.scrollArea_3.setAutoFillBackground(False)
        self.scrollArea_3.setStyleSheet("background-color: rgba(255, 255, 255, 0.1);")
        self.scrollArea_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_3.setLineWidth(1)
        self.scrollArea_3.setMidLineWidth(1)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 55, 16))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_8.setGeometry(QtCore.QRect(11, 11, 872, 411))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 30, 831, 371))
        self.textBrowser_5.setStyleSheet("border:none;\n"
"")
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 470, 872, 411))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_6.setGeometry(QtCore.QRect(20, 30, 831, 371))
        self.textBrowser_6.setStyleSheet("border:none;")
        self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_15.addWidget(self.scrollArea_3)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(600, -1, -1, -1)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_37.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_37.addWidget(self.pushButton_6)
        self.verticalLayout_15.addLayout(self.horizontalLayout_37)
        self.tabWidget_4.addTab(self.tab_17, icon, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.label_35 = QtWidgets.QLabel(self.tab_18)
        self.label_35.setGeometry(QtCore.QRect(170, 190, 611, 221))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(48)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.tabWidget_4.addTab(self.tab_18, icon2, "")
        self.verticalLayout_2.addWidget(self.tabWidget_4)
        self.stackedWidget.addWidget(self.page_UNet)
        self.page_Dataset = QtWidgets.QWidget()
        self.page_Dataset.setObjectName("page_Dataset")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_Dataset)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.page_Dataset)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(36)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_Dataset)
        self.tabWidget_3.setAutoFillBackground(True)
        self.tabWidget_3.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_camera = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_camera.setFont(font)
        self.label_camera.setStyleSheet("background-color: rgba(104, 104, 104, 0.1);")
        self.label_camera.setMidLineWidth(0)
        self.label_camera.setTextFormat(QtCore.Qt.AutoText)
        self.label_camera.setScaledContents(True)
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setOpenExternalLinks(True)
        self.label_camera.setObjectName("label_camera")
        self.horizontalLayout_15.addWidget(self.label_camera)
        self.line = QtWidgets.QFrame(self.tab_6)
        self.line.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_15.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_camera_pix_path = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_camera_pix_path.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.lineEdit_camera_pix_path.setFont(font)
        self.lineEdit_camera_pix_path.setStyleSheet("color: rgb(255, 0, 0);")
        self.lineEdit_camera_pix_path.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_camera_pix_path.setClearButtonEnabled(True)
        self.lineEdit_camera_pix_path.setObjectName("lineEdit_camera_pix_path")
        self.horizontalLayout_6.addWidget(self.lineEdit_camera_pix_path)
        self.pushButton_load_pix_path = QtWidgets.QPushButton(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_load_pix_path.setFont(font)
        self.pushButton_load_pix_path.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_load_pix_path.setIcon(icon3)
        self.pushButton_load_pix_path.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_load_pix_path.setObjectName("pushButton_load_pix_path")
        self.horizontalLayout_6.addWidget(self.pushButton_load_pix_path)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.textBrowser_dataset_show = QtWidgets.QTextBrowser(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textBrowser_dataset_show.setFont(font)
        self.textBrowser_dataset_show.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_dataset_show.setStyleSheet("border:none;\n"
"background-color: rgba(104, 104, 104, 0.1);")
        self.textBrowser_dataset_show.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_dataset_show.setObjectName("textBrowser_dataset_show")
        self.verticalLayout_5.addWidget(self.textBrowser_dataset_show)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.horizontalLayout_15.setStretch(0, 7)
        self.horizontalLayout_15.setStretch(1, 1)
        self.horizontalLayout_15.setStretch(2, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_open_camera = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_open_camera.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_open_camera.setObjectName("pushButton_open_camera")
        self.horizontalLayout_4.addWidget(self.pushButton_open_camera)
        self.pushButton_get_current = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_get_current.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_get_current.setFont(font)
        self.pushButton_get_current.setStyleSheet("color:rgb(255, 0, 0);")
        self.pushButton_get_current.setObjectName("pushButton_get_current")
        self.horizontalLayout_4.addWidget(self.pushButton_get_current)
        self.pushButton_open_file = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_open_file.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_open_file.setFont(font)
        self.pushButton_open_file.setStyleSheet("")
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.horizontalLayout_4.addWidget(self.pushButton_open_file)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_6, icon4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.textEdit_climbdata = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_climbdata.setObjectName("textEdit_climbdata")
        self.verticalLayout_7.addWidget(self.textEdit_climbdata)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/television.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_7, icon5, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_20 = QtWidgets.QLabel(self.tab_8)
        self.label_20.setGeometry(QtCore.QRect(180, 160, 611, 221))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(48)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.tabWidget_3.addTab(self.tab_8, icon2, "")
        self.verticalLayout_6.addWidget(self.tabWidget_3)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 11)
        self.stackedWidget.addWidget(self.page_Dataset)
        self.page_yolo = QtWidgets.QWidget()
        self.page_yolo.setObjectName("page_yolo")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_yolo)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.page_yolo)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(36)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(255, 85, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.page_yolo)
        self.tabWidget_5.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget_5.setTabBarAutoHide(True)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_9)
        self.scrollArea_2.setAcceptDrops(False)
        self.scrollArea_2.setStyleSheet("background:transparent;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 24, 700))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 700))
        self.scrollAreaWidgetContents_2.setBaseSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_yolo_predict = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_yolo_predict.setGeometry(QtCore.QRect(20, 10, 611, 371))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_yolo_predict.setFont(font)
        self.label_yolo_predict.setStyleSheet("background-color: rgba(206, 206, 206, 0.4);")
        self.label_yolo_predict.setText("")
        self.label_yolo_predict.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yolo_predict.setWordWrap(True)
        self.label_yolo_predict.setObjectName("label_yolo_predict")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 420, 611, 271))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("border:none;\n"
"background-color: rgba(211, 211, 211, 0.4);\n"
"")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setGeometry(QtCore.QRect(20, 390, 611, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("\n"
"background-color: rgba(211, 211, 211, 0.4);\n"
"")
        self.label_12.setObjectName("label_12")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_19.addWidget(self.scrollArea_2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 207, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.radioButton_camera = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_camera.setChecked(True)
        self.radioButton_camera.setObjectName("radioButton_camera")
        self.horizontalLayout_17.addWidget(self.radioButton_camera)
        self.radioButton_videos = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_videos.setObjectName("radioButton_videos")
        self.horizontalLayout_17.addWidget(self.radioButton_videos)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_yolo_predict_videopath = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_yolo_predict_videopath.setGeometry(QtCore.QRect(10, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_yolo_predict_videopath.setFont(font)
        self.lineEdit_yolo_predict_videopath.setStyleSheet("background:transparent;")
        self.lineEdit_yolo_predict_videopath.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yolo_predict_videopath.setReadOnly(True)
        self.lineEdit_yolo_predict_videopath.setClearButtonEnabled(True)
        self.lineEdit_yolo_predict_videopath.setObjectName("lineEdit_yolo_predict_videopath")
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_yolo_predict_play = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_yolo_predict_play.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_yolo_predict_play.setObjectName("pushButton_yolo_predict_play")
        self.horizontalLayout_18.addWidget(self.pushButton_yolo_predict_play)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_12)
        self.horizontalLayout_19.setStretch(0, 5)
        self.horizontalLayout_19.setStretch(1, 2)
        self.tabWidget_5.addTab(self.tab_9, icon, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_13 = QtWidgets.QLabel(self.tab_10)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 871, 321))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(28)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.tabWidget_5.addTab(self.tab_10, icon1, "")
        self.verticalLayout_10.addWidget(self.tabWidget_5)
        self.stackedWidget.addWidget(self.page_yolo)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1194, 29))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("border-image: url(:/timg (3).jpg);")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.menu_3.setFont(font)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menu_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.menu_4.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/football.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_4.setIcon(icon6)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu_3)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(200, 183))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.dockWidget_2.setFont(font)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setContentsMargins(1, 0, 0, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.treeView.setFont(font)
        self.treeView.setAutoFillBackground(True)
        self.treeView.setStyleSheet("background-color: rgba(188, 188, 188, 0.1);")
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(40, -1, 40, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_4 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(40, 30))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setIconSize(QtCore.QSize(40, 30))
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setIconSize(QtCore.QSize(40, 30))
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.actionnew_window = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnew_window.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionnew_window.setFont(font)
        self.actionnew_window.setObjectName("actionnew_window")
        self.actionsavefile = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsavefile.setIcon(icon8)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionsavefile.setFont(font)
        self.actionsavefile.setObjectName("actionsavefile")
        self.actionquit = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionquit.setIcon(icon9)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionquit.setFont(font)
        self.actionquit.setObjectName("actionquit")
        self.actionself_center = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionself_center.setFont(font)
        self.actionself_center.setObjectName("actionself_center")
        self.actionResNet_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionResNet_2.setFont(font)
        self.actionResNet_2.setObjectName("actionResNet_2")
        self.actionVGGNet = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionVGGNet.setFont(font)
        self.actionVGGNet.setObjectName("actionVGGNet")
        self.actionAlexNet = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionAlexNet.setFont(font)
        self.actionAlexNet.setObjectName("actionAlexNet")
        self.actionyolov3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionyolov3.setFont(font)
        self.actionyolov3.setObjectName("actionyolov3")
        self.actionyolov4 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionyolov4.setFont(font)
        self.actionyolov4.setObjectName("actionyolov4")
        self.actionyolov5 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionyolov5.setFont(font)
        self.actionyolov5.setObjectName("actionyolov5")
        self.actionuse = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionuse.setFont(font)
        self.actionuse.setObjectName("actionuse")
        self.actionopendata = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionopendata.setFont(font)
        self.actionopendata.setObjectName("actionopendata")
        self.actionmakedata = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.actionmakedata.setFont(font)
        self.actionmakedata.setObjectName("actionmakedata")
        self.actionUNet = QtWidgets.QAction(MainWindow)
        self.actionUNet.setObjectName("actionUNet")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setIcon(icon3)
        self.actionnew.setObjectName("actionnew")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/seting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon10)
        self.actionSetting.setObjectName("actionSetting")
        self.actionquitApp = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/退出.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionquitApp.setIcon(icon11)
        self.actionquitApp.setObjectName("actionquitApp")
        self.actiondatabase = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newfilepath/Icon/数据集.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondatabase.setIcon(icon12)
        self.actiondatabase.setObjectName("actiondatabase")
        self.menu.addAction(self.actionnew_window)
        self.menu.addSeparator()
        self.menu.addAction(self.actionsavefile)
        self.menu.addSeparator()
        self.menu.addAction(self.actionquit)
        self.menu_2.addAction(self.actionself_center)
        self.menu_4.addAction(self.actionResNet_2)
        self.menu_4.addAction(self.actionVGGNet)
        self.menu_4.addAction(self.actionAlexNet)
        self.menu_4.addAction(self.actionUNet)
        self.menu_5.addAction(self.actionyolov3)
        self.menu_5.addAction(self.actionyolov4)
        self.menu_5.addAction(self.actionyolov5)
        self.menu_3.addAction(self.menu_4.menuAction())
        self.menu_3.addAction(self.menu_5.menuAction())
        self.menu_6.addAction(self.actionuse)
        self.menu_7.addAction(self.actionopendata)
        self.menu_7.addAction(self.actionmakedata)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.toolBar.addAction(self.actionnew)
        self.toolBar.addAction(self.actionquitApp)
        self.toolBar_2.addAction(self.actionSetting)
        self.toolBar_3.addAction(self.actiondatabase)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XHao Net Studio"))
        self.label_9.setText(_translate("MainWindow", "ResNet 模 型"))
        self.groupBox.setTitle(_translate("MainWindow", "自调参数"))
        self.label_17.setText(_translate("MainWindow", "序 号："))
        self.label.setText(_translate("MainWindow", "层 数："))
        self.comboBox_floor.setItemText(0, _translate("MainWindow", "18"))
        self.comboBox_floor.setItemText(1, _translate("MainWindow", "34"))
        self.comboBox_floor.setItemText(2, _translate("MainWindow", "50"))
        self.comboBox_floor.setItemText(3, _translate("MainWindow", "101"))
        self.label_6.setText(_translate("MainWindow", "类别数："))
        self.label_2.setText(_translate("MainWindow", "epoch："))
        self.label_3.setText(_translate("MainWindow", "batch："))
        self.label_4.setText(_translate("MainWindow", "LR ："))
        self.label_5.setText(_translate("MainWindow", "数据集："))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "数据集文件路径"))
        self.pushButton_ResNet_load.setText(_translate("MainWindow", "加载"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XHao Net Studio @2021 QQ:2510383889</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "终端"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "结果可视化"))
        self.checkBox_ResNet.setText(_translate("MainWindow", "保存训练过程:"))
        self.pushButton_ResNet_train.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_ResNet_cancel.setText(_translate("MainWindow", "取消训练"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "训练"))
        self.label_19.setText(_translate("MainWindow", "数据集："))
        self.lineEdit_predict_imgpath.setPlaceholderText(_translate("MainWindow", "数据（图片）地址"))
        self.pushButton_ResNet_predict_imgpath.setText(_translate("MainWindow", "加载"))
        self.label_24.setText(_translate("MainWindow", "模型参数："))
        self.lineEdit_predict_netpath.setPlaceholderText(_translate("MainWindow", "网络模型参数数据地址"))
        self.pushButton_ResNet_predict_netpath.setText(_translate("MainWindow", "加载"))
        self.scrollArea.setStatusTip(_translate("MainWindow", "数据区（图片 or 视频）"))
        self.groupBox_3.setTitle(_translate("MainWindow", "待测数据"))
        self.groupBox_4.setTitle(_translate("MainWindow", "结果展示"))
        self.pushButton.setText(_translate("MainWindow", "开始预测"))
        self.pushButton_2.setText(_translate("MainWindow", "清空"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "预测"))
        self.label_21.setText(_translate("MainWindow", "功能暂未开放！"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "模型代码"))
        self.label_10.setText(_translate("MainWindow", "UNet 模 型"))
        self.groupBox_7.setTitle(_translate("MainWindow", "自调参数"))
        self.label_26.setText(_translate("MainWindow", "序 号："))
        self.label_27.setText(_translate("MainWindow", "层 数："))
        self.comboBox_floor_3.setItemText(0, _translate("MainWindow", "18"))
        self.comboBox_floor_3.setItemText(1, _translate("MainWindow", "34"))
        self.comboBox_floor_3.setItemText(2, _translate("MainWindow", "50"))
        self.comboBox_floor_3.setItemText(3, _translate("MainWindow", "101"))
        self.label_28.setText(_translate("MainWindow", "类别数："))
        self.label_29.setText(_translate("MainWindow", "epoch："))
        self.label_30.setText(_translate("MainWindow", "batch："))
        self.label_31.setText(_translate("MainWindow", "LR ："))
        self.label_32.setText(_translate("MainWindow", "数据集："))
        self.pushButton_ResNet_load_3.setText(_translate("MainWindow", "加载"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_15), _translate("MainWindow", "终端"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_16), _translate("MainWindow", "结果可视化"))
        self.checkBox_ResNet_3.setText(_translate("MainWindow", "保存训练过程:"))
        self.pushButton_ResNet_train_3.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_ResNet_cancel_3.setText(_translate("MainWindow", "取消训练"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("MainWindow", "训练"))
        self.label_33.setText(_translate("MainWindow", "数据集："))
        self.lineEdit_predict_imgpath_3.setPlaceholderText(_translate("MainWindow", "数据（图片）地址"))
        self.pushButton_ResNet_predict_imgpath_3.setText(_translate("MainWindow", "加载"))
        self.label_34.setText(_translate("MainWindow", "模型参数："))
        self.lineEdit_predict_netpath_3.setPlaceholderText(_translate("MainWindow", "网络模型参数数据地址"))
        self.pushButton_ResNet_predict_netpath_3.setText(_translate("MainWindow", "加载"))
        self.scrollArea_3.setStatusTip(_translate("MainWindow", "数据区（图片 or 视频）"))
        self.groupBox_8.setTitle(_translate("MainWindow", "待测数据"))
        self.groupBox_9.setTitle(_translate("MainWindow", "结果展示"))
        self.pushButton_5.setText(_translate("MainWindow", "开始预测"))
        self.pushButton_6.setText(_translate("MainWindow", "清空"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "预测"))
        self.label_35.setText(_translate("MainWindow", "功能暂未开放！"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_18), _translate("MainWindow", "模型代码"))
        self.label_8.setText(_translate("MainWindow", "数 据 采 集"))
        self.label_camera.setText(_translate("MainWindow", "当前未检测到摄像头!\n"
"\n"
"~_~请打开摄像头或者加载本地资源~_~"))
        self.lineEdit_camera_pix_path.setPlaceholderText(_translate("MainWindow", "图片保存文件夹"))
        self.textBrowser_dataset_show.setStatusTip(_translate("MainWindow", "展示获取的帧"))
        self.textBrowser_dataset_show.setPlaceholderText(_translate("MainWindow", "获取的帧"))
        self.pushButton_open_camera.setText(_translate("MainWindow", "打开相机"))
        self.pushButton_get_current.setText(_translate("MainWindow", "捕获当前帧"))
        self.pushButton_open_file.setText(_translate("MainWindow", "打开影像"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "相机/本地资源"))
        self.label_7.setText(_translate("MainWindow", "网络地址："))
        self.pushButton_9.setText(_translate("MainWindow", "开始爬取"))
        self.textEdit_climbdata.setPlaceholderText(_translate("MainWindow", "爬取结果"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "网络爬取"))
        self.label_20.setText(_translate("MainWindow", "功能暂未开放！"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "数据处理"))
        self.label_11.setText(_translate("MainWindow", "yolo 模 型"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XHao Net Studio @2021 QQ:2510383889</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "console："))
        self.groupBox_2.setTitle(_translate("MainWindow", "模式选择"))
        self.radioButton_camera.setText(_translate("MainWindow", "camera"))
        self.radioButton_videos.setText(_translate("MainWindow", "videos"))
        self.groupBox_5.setTitle(_translate("MainWindow", "路径加载"))
        self.lineEdit_yolo_predict_videopath.setPlaceholderText(_translate("MainWindow", "视频文件路径"))
        self.pushButton_yolo_predict_play.setText(_translate("MainWindow", "开始播放"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_9), _translate("MainWindow", "预测"))
        self.label_13.setText(_translate("MainWindow", "😂😜😡👻🐴 先等等！😂😜😡👻🐴"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_10), _translate("MainWindow", "训练数据集"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "模型选择"))
        self.menu_4.setTitle(_translate("MainWindow", "图片分类"))
        self.menu_5.setTitle(_translate("MainWindow", "目标检测"))
        self.menu_6.setTitle(_translate("MainWindow", "帮助"))
        self.menu_7.setTitle(_translate("MainWindow", "数据集"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "工作目录"))
        self.pushButton_4.setText(_translate("MainWindow", "加载目录"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.actionnew_window.setText(_translate("MainWindow", "新建窗口"))
        self.actionsavefile.setText(_translate("MainWindow", "保存文件"))
        self.actionquit.setText(_translate("MainWindow", "退出"))
        self.actionquit.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionself_center.setText(_translate("MainWindow", "个人中心"))
        self.actionResNet_2.setText(_translate("MainWindow", "ResNet"))
        self.actionVGGNet.setText(_translate("MainWindow", "VGGNet"))
        self.actionAlexNet.setText(_translate("MainWindow", "AlexNet"))
        self.actionyolov3.setText(_translate("MainWindow", "yolov3"))
        self.actionyolov4.setText(_translate("MainWindow", "yolov4"))
        self.actionyolov5.setText(_translate("MainWindow", "yolov5"))
        self.actionuse.setText(_translate("MainWindow", "使用"))
        self.actionopendata.setText(_translate("MainWindow", "打开本地数据集"))
        self.actionmakedata.setText(_translate("MainWindow", "自定义制作数据集"))
        self.actionUNet.setText(_translate("MainWindow", "UNet"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionnew.setToolTip(_translate("MainWindow", "new"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionSetting.setToolTip(_translate("MainWindow", "Setting"))
        self.actionSetting.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionquitApp.setText(_translate("MainWindow", "quitApp"))
        self.actionquitApp.setToolTip(_translate("MainWindow", "quitApp"))
        self.actionquitApp.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actiondatabase.setText(_translate("MainWindow", "database"))
        self.actiondatabase.setToolTip(_translate("MainWindow", "database"))
import Ui_logic_rc