# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1112, 710)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuBar = QtWidgets.QWidget(Form)
        self.menuBar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menuBar.setStyleSheet("#menuBar{border-image: url(:/新前缀/images/sky_cloud.jpg);}")
        self.menuBar.setObjectName("menuBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menuBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_toggle = QtWidgets.QWidget(self.menuBar)
        self.frame_toggle.setMinimumSize(QtCore.QSize(201, 50))
        self.frame_toggle.setMaximumSize(QtCore.QSize(201, 50))
        self.frame_toggle.setStyleSheet("")
        self.frame_toggle.setObjectName("frame_toggle")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toggle)
        self.btn_toggle.setGeometry(QtCore.QRect(21, 6, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btn_toggle.setFont(font)
        self.btn_toggle.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.06, y1:0.108, x2:1, y2:1, stop:0.179104 rgba(23, 165, 57, 246), stop:1 rgba(25, 235, 224, 255));\n"
"    border-radius:20px;}\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.91, y2:0.9375, stop:0.149254 rgba(95, 235, 192, 255), stop:0.935323 rgba(23, 165, 57, 229));\n"
"    border-radius:20px;}\n"
"QPushButton::pressed{\n"
"    color: rgb(170, 0, 0);}\n"
"")
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout_3.addWidget(self.frame_toggle, 0, QtCore.Qt.AlignTop)
        self.addition_bar = QtWidgets.QWidget(self.menuBar)
        self.addition_bar.setMinimumSize(QtCore.QSize(600, 50))
        self.addition_bar.setMaximumSize(QtCore.QSize(600, 50))
        self.addition_bar.setStyleSheet("QToolButton{\n"
"background:transparent;\n"
"}\n"
"QToolButton::hover {\n"
"    background-color: rgb(192, 226, 255);\n"
"    border-bottom: 2px solid rgb(9, 187, 7);\n"
"    border-top: 2px solid rgb(9, 187, 7);\n"
"    border-radius:10px;\n"
"}")
        self.addition_bar.setObjectName("addition_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.addition_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_4 = QtWidgets.QFrame(self.addition_bar)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.tbtn_add_Activation = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_Activation.setToolTipDuration(0)
        self.tbtn_add_Activation.setStatusTip("")
        self.tbtn_add_Activation.setStyleSheet("background:transparent;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/新前缀/images/A.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_Activation.setIcon(icon)
        self.tbtn_add_Activation.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_Activation.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_Activation.setAutoRaise(True)
        self.tbtn_add_Activation.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_Activation.setObjectName("tbtn_add_Activation")
        self.horizontalLayout_2.addWidget(self.tbtn_add_Activation, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tbtn_add_BatchNorm1d = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_BatchNorm1d.setToolTipDuration(0)
        self.tbtn_add_BatchNorm1d.setStyleSheet("background:transparent;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/新前缀/images/B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_BatchNorm1d.setIcon(icon1)
        self.tbtn_add_BatchNorm1d.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_BatchNorm1d.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_BatchNorm1d.setAutoRaise(True)
        self.tbtn_add_BatchNorm1d.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_BatchNorm1d.setObjectName("tbtn_add_BatchNorm1d")
        self.horizontalLayout_2.addWidget(self.tbtn_add_BatchNorm1d)
        self.tbtn_add_BatchNorm2d = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_BatchNorm2d.setToolTipDuration(0)
        self.tbtn_add_BatchNorm2d.setStyleSheet("background:transparent;")
        self.tbtn_add_BatchNorm2d.setIcon(icon1)
        self.tbtn_add_BatchNorm2d.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_BatchNorm2d.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_BatchNorm2d.setAutoRaise(True)
        self.tbtn_add_BatchNorm2d.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_BatchNorm2d.setObjectName("tbtn_add_BatchNorm2d")
        self.horizontalLayout_2.addWidget(self.tbtn_add_BatchNorm2d)
        self.tbtn_add_Conv = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_Conv.setToolTipDuration(0)
        self.tbtn_add_Conv.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/新前缀/images/C.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_Conv.setIcon(icon2)
        self.tbtn_add_Conv.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_Conv.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_Conv.setAutoRaise(True)
        self.tbtn_add_Conv.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_Conv.setObjectName("tbtn_add_Conv")
        self.horizontalLayout_2.addWidget(self.tbtn_add_Conv, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tbtn_add_dropout = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_dropout.setToolTipDuration(0)
        self.tbtn_add_dropout.setStyleSheet("background:transparent;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/新前缀/images/D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_dropout.setIcon(icon3)
        self.tbtn_add_dropout.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_dropout.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_dropout.setAutoRaise(True)
        self.tbtn_add_dropout.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_dropout.setObjectName("tbtn_add_dropout")
        self.horizontalLayout_2.addWidget(self.tbtn_add_dropout, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tbtn_add_FlattenLayer = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_FlattenLayer.setToolTipDuration(0)
        self.tbtn_add_FlattenLayer.setStyleSheet("background:transparent;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/新前缀/images/F.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_FlattenLayer.setIcon(icon4)
        self.tbtn_add_FlattenLayer.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_FlattenLayer.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_FlattenLayer.setAutoRaise(True)
        self.tbtn_add_FlattenLayer.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_FlattenLayer.setObjectName("tbtn_add_FlattenLayer")
        self.horizontalLayout_2.addWidget(self.tbtn_add_FlattenLayer, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tbtn_add_Linear = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_Linear.setToolTipDuration(0)
        self.tbtn_add_Linear.setStyleSheet("background:transparent;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/新前缀/images/L.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_Linear.setIcon(icon5)
        self.tbtn_add_Linear.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_Linear.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_Linear.setAutoRaise(True)
        self.tbtn_add_Linear.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_Linear.setObjectName("tbtn_add_Linear")
        self.horizontalLayout_2.addWidget(self.tbtn_add_Linear)
        self.tbtn_add_Maxpool = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_add_Maxpool.setToolTipDuration(0)
        self.tbtn_add_Maxpool.setStyleSheet("background:transparent;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/新前缀/images/M.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_add_Maxpool.setIcon(icon6)
        self.tbtn_add_Maxpool.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_add_Maxpool.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_add_Maxpool.setAutoRaise(True)
        self.tbtn_add_Maxpool.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_add_Maxpool.setObjectName("tbtn_add_Maxpool")
        self.horizontalLayout_2.addWidget(self.tbtn_add_Maxpool, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.line_2 = QtWidgets.QFrame(self.addition_bar)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.tbtn_makeDatasets = QtWidgets.QToolButton(self.addition_bar)
        self.tbtn_makeDatasets.setToolTipDuration(0)
        self.tbtn_makeDatasets.setStyleSheet("background:transparent;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/新前缀/images/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_makeDatasets.setIcon(icon7)
        self.tbtn_makeDatasets.setIconSize(QtCore.QSize(50, 50))
        self.tbtn_makeDatasets.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbtn_makeDatasets.setAutoRaise(True)
        self.tbtn_makeDatasets.setArrowType(QtCore.Qt.NoArrow)
        self.tbtn_makeDatasets.setObjectName("tbtn_makeDatasets")
        self.horizontalLayout_2.addWidget(self.tbtn_makeDatasets)
        self.line_3 = QtWidgets.QFrame(self.addition_bar)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_3.addWidget(self.addition_bar, 0, QtCore.Qt.AlignTop)
        self.line = QtWidgets.QFrame(self.menuBar)
        self.line.setStyleSheet("background:transparent;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout.addWidget(self.menuBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_bars = QtWidgets.QWidget(Form)
        self.left_bars.setMinimumSize(QtCore.QSize(0, 0))
        self.left_bars.setMaximumSize(QtCore.QSize(201, 16777215))
        self.left_bars.setStyleSheet(".QWidget{border-image: url(:/新前缀/images/sky_cloud.jpg);}\n"
"")
        self.left_bars.setObjectName("left_bars")
        self.listWidget = QtWidgets.QListWidget(self.left_bars)
        self.listWidget.setGeometry(QtCore.QRect(0, 70, 201, 511))
        self.listWidget.setStyleSheet("QListWidget, QListView, QTreeWidget, QTreeView {\n"
"    outline: None;\n"
"}\n"
"/*设置左侧选项的最小最大宽度,文字颜色和背景颜色*/\n"
"QListWidget {\n"
"    border:none;\n"
"    background:transparent;\n"
"}\n"
"/*设置左侧选项的最小高度*/\n"
"QListWidget::item{\n"
"    min-height:120px;\n"
"}\n"
"/*被选中时的背景颜色和左边框颜色*/\n"
"QListWidget::item:selected {\n"
"    color: rgb(0,0,0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-left: 2px solid rgb(9, 187, 7);\n"
"    border-left-radius:15px;\n"
"}\n"
"\n"
"/*鼠标悬停颜色*/\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(192, 226, 255);\n"
"    border-left: 2px solid rgb(9, 187, 7);\n"
"    border-radius:15px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(32)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setUnderline(True)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setUnderline(True)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.left_bars)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(110)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(180, 107, 158);")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.home)
        self.Designer = QtWidgets.QWidget()
        self.Designer.setObjectName("Designer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Designer)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.Designer)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2500, 28))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(2500, 0))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.editor_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.editor_layout.setContentsMargins(0, 0, 0, 0)
        self.editor_layout.setObjectName("editor_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.btn_generate = QtWidgets.QPushButton(self.Designer)
        self.btn_generate.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.btn_generate.setFont(font)
        self.btn_generate.setObjectName("btn_generate")
        self.verticalLayout_3.addWidget(self.btn_generate)
        self.stackedWidget.addWidget(self.Designer)
        self.Train = QtWidgets.QWidget()
        self.Train.setObjectName("Train")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Train)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.train_btnbar = QtWidgets.QTabWidget(self.Train)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.train_btnbar.setFont(font)
        self.train_btnbar.setStyleSheet("#train_setting{\n"
"background-color: rgb(218, 218, 218);}\n"
"#tab{\n"
"background-color: rgb(218, 218, 218);}")
        self.train_btnbar.setTabPosition(QtWidgets.QTabWidget.South)
        self.train_btnbar.setObjectName("train_btnbar")
        self.train_setting = QtWidgets.QWidget()
        self.train_setting.setStyleSheet("")
        self.train_setting.setObjectName("train_setting")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.train_setting)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.train_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{background-color: rgba(206, 206, 206, 0.4);}")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(50, -1, 50, -1)
        self.gridLayout.setHorizontalSpacing(100)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.btn_loadNetMoudle = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_loadNetMoudle.setFont(font)
        self.btn_loadNetMoudle.setObjectName("btn_loadNetMoudle")
        self.horizontalLayout_10.addWidget(self.btn_loadNetMoudle)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.doubleSpinBox_LR = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.doubleSpinBox_LR.setFont(font)
        self.doubleSpinBox_LR.setAutoFillBackground(True)
        self.doubleSpinBox_LR.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.doubleSpinBox_LR.setWrapping(True)
        self.doubleSpinBox_LR.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_LR.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_LR.setDecimals(5)
        self.doubleSpinBox_LR.setMaximum(1.0)
        self.doubleSpinBox_LR.setSingleStep(1e-06)
        self.doubleSpinBox_LR.setProperty("value", 0.001)
        self.doubleSpinBox_LR.setObjectName("doubleSpinBox_LR")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_LR)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.btn_loadDatasets = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_loadDatasets.setFont(font)
        self.btn_loadDatasets.setObjectName("btn_loadDatasets")
        self.horizontalLayout_8.addWidget(self.btn_loadDatasets)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.spinBox_batch = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_batch.setFont(font)
        self.spinBox_batch.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_batch.setWrapping(True)
        self.spinBox_batch.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_batch.setMaximum(999)
        self.spinBox_batch.setSingleStep(1)
        self.spinBox_batch.setProperty("value", 128)
        self.spinBox_batch.setObjectName("spinBox_batch")
        self.horizontalLayout_9.addWidget(self.spinBox_batch)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.spinBox_exercise = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_exercise.setFont(font)
        self.spinBox_exercise.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_exercise.setWrapping(True)
        self.spinBox_exercise.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_exercise.setMaximum(1000)
        self.spinBox_exercise.setObjectName("spinBox_exercise")
        self.horizontalLayout_4.addWidget(self.spinBox_exercise)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinBox_epoch = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_epoch.setFont(font)
        self.spinBox_epoch.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);")
        self.spinBox_epoch.setWrapping(True)
        self.spinBox_epoch.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_epoch.setMaximum(1000)
        self.spinBox_epoch.setProperty("value", 10)
        self.spinBox_epoch.setObjectName("spinBox_epoch")
        self.horizontalLayout_7.addWidget(self.spinBox_epoch)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_train_save = QtWidgets.QCheckBox(self.train_setting)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btn_train_save.setFont(font)
        self.btn_train_save.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_train_save.setAutoFillBackground(False)
        self.btn_train_save.setStyleSheet("background:transparent;")
        self.btn_train_save.setChecked(True)
        self.btn_train_save.setTristate(False)
        self.btn_train_save.setObjectName("btn_train_save")
        self.horizontalLayout_5.addWidget(self.btn_train_save)
        self.btn_train = QtWidgets.QPushButton(self.train_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_train.sizePolicy().hasHeightForWidth())
        self.btn_train.setSizePolicy(sizePolicy)
        self.btn_train.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_train.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btn_train.setFont(font)
        self.btn_train.setObjectName("btn_train")
        self.horizontalLayout_5.addWidget(self.btn_train)
        self.btn_train_stop = QtWidgets.QPushButton(self.train_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_train_stop.sizePolicy().hasHeightForWidth())
        self.btn_train_stop.setSizePolicy(sizePolicy)
        self.btn_train_stop.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_train_stop.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.btn_train_stop.setFont(font)
        self.btn_train_stop.setObjectName("btn_train_stop")
        self.horizontalLayout_5.addWidget(self.btn_train_stop)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.train_btnbar.addTab(self.train_setting, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.chart_layout = QtWidgets.QVBoxLayout(self.tab)
        self.chart_layout.setObjectName("chart_layout")
        self.train_btnbar.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.train_btnbar)
        self.stackedWidget.addWidget(self.Train)
        self.console = QtWidgets.QTextBrowser(self.splitter)
        self.console.setMinimumSize(QtCore.QSize(0, 100))
        self.console.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.console.setFont(font)
        self.console.setStyleSheet("border:none;\n"
"background-color: rgba(211, 211, 211, 0.4);\n"
"")
        self.console.setReadOnly(True)
        self.console.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.console.setOpenExternalLinks(True)
        self.console.setObjectName("console")
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.train_btnbar.setCurrentIndex(0)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_toggle.setText(_translate("Form", "菜单"))
        self.tbtn_add_Activation.setToolTip(_translate("Form", "Relu / Sigmod / Than"))
        self.tbtn_add_Activation.setText(_translate("Form", "..."))
        self.tbtn_add_BatchNorm1d.setToolTip(_translate("Form", "BatchNorm1d"))
        self.tbtn_add_BatchNorm1d.setText(_translate("Form", "..."))
        self.tbtn_add_BatchNorm2d.setToolTip(_translate("Form", "BatchNorm2d"))
        self.tbtn_add_BatchNorm2d.setText(_translate("Form", "..."))
        self.tbtn_add_Conv.setToolTip(_translate("Form", "Conv2d"))
        self.tbtn_add_Conv.setText(_translate("Form", "..."))
        self.tbtn_add_dropout.setToolTip(_translate("Form", "Dropout"))
        self.tbtn_add_dropout.setText(_translate("Form", "..."))
        self.tbtn_add_FlattenLayer.setToolTip(_translate("Form", "FlattenLayer"))
        self.tbtn_add_FlattenLayer.setText(_translate("Form", "..."))
        self.tbtn_add_Linear.setToolTip(_translate("Form", "MaxPool2d"))
        self.tbtn_add_Linear.setText(_translate("Form", "..."))
        self.tbtn_add_Maxpool.setToolTip(_translate("Form", "MaxPool2d"))
        self.tbtn_add_Maxpool.setText(_translate("Form", "..."))
        self.tbtn_makeDatasets.setToolTip(_translate("Form", "makeDatasets"))
        self.tbtn_makeDatasets.setText(_translate("Form", "..."))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "ViTorch"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Designer"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Train"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Form", "ViTorch"))
        self.btn_generate.setToolTip(_translate("Form", "生成网络模型代码文件"))
        self.btn_generate.setText(_translate("Form", "generate"))
        self.groupBox.setTitle(_translate("Form", "自调参数"))
        self.label.setText(_translate("Form", "模 型："))
        self.btn_loadNetMoudle.setText(_translate("Form", "加载"))
        self.label_5.setText(_translate("Form", "LR ："))
        self.label_7.setText(_translate("Form", "数据集："))
        self.lineEdit.setPlaceholderText(_translate("Form", "数据集文件路径(内含train、test文件夹)"))
        self.btn_loadDatasets.setText(_translate("Form", "加载"))
        self.label_4.setText(_translate("Form", "batch："))
        self.label_17.setText(_translate("Form", "序 号："))
        self.label_3.setText(_translate("Form", "epoch："))
        self.btn_train_save.setText(_translate("Form", "保存训练过程:"))
        self.btn_train.setText(_translate("Form", "开始训练"))
        self.btn_train_stop.setText(_translate("Form", "终止训练"))
        self.train_btnbar.setTabText(self.train_btnbar.indexOf(self.train_setting), _translate("Form", "参数设置"))
        self.train_btnbar.setTabText(self.train_btnbar.indexOf(self.tab), _translate("Form", "曲线绘制"))
        self.console.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Vitorch console @2021 QQ:2510383889</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
from mainWindow.lib import resouses_rc